export const categories = [
    {
        id: 'a',
        name: 'House Chores',
        sub: [
            {
                id: 'a1',
                name: 'Home Cook',
                unit: '/menu set',
                label1: 'Type of Service',
                label2: 'Menu',
                option1: ['Delivery', 'Cook at Home', 'Cooking Class'],
                option2: ['Asian', 'Western', 'Vegetarian', 'Pastry', 'Halal'],
            },
            {
                id: 'a2',
                name: 'Dishwashing',
                unit: '/hour',
                label1: 'Gender',
                option1: ['Male', 'Female'],
            },
            {
                id: 'a3',
                name: 'Trash Pick-Up',
                unit: '/kg',
                label1: 'Type of Service',
                label2: 'Type of Service',
                option1: ['Trash Pick-Up', 'Garbage Cleaning', 'Trash Collecting', 'Sorting Trash'],
                option2: ['Organic Waste', 'Inorganic Waste', 'Recyclable Waste', 'Electronic Waste', 'Furnitures Waste', 'Paper Waste'],
            },
            {
                id: 'a4',
                name: 'Laundry',
                unit: '/kg',
                label1: 'Laundry Service',
                option1: ['Laundry', 'Ironing', 'Dry Clean', 'Shoe Laundry', 'Bag Laundry', 'Doll Laundry', 'Pillow Laundry'],
            },
            {
                id: 'a5',
                name: 'Delivery',
                unit: '/delivery',
                label1: 'Delivery Item',
                option1: ['Cooking Gas', 'Drinking Water Gallon'],
            },
        ],
    },
    {
        id: 'b',
        name: 'House Cleaning & Organizing',
        sub: [
            {
                id: 'b1',
                name: 'House Cleaning',
                unit: '/hour',
                label1: 'Cleaning Service',
                option1: [
                    'Room Cleaning',
                    'Toilet Cleaning',
                    'Window Cleaning',
                    'Ceiling Cleaning',
                    'Attic Cleaning',
                    'Vacuum Cleaning',
                    'Rug Cleaning',
                    'Bed Cleaning',
                    'Leather Furniture Cleaning',
                    'Home Appliances Cleaning',
                    'Sanitizing',
                ],
            },
            {
                id: 'b2',
                name: 'House Handyman',
                unit: '/hour',
                label1: 'House Handyman Service',
                option1: ['Fixing Broken Furniture', 'Assembling Furniture', 'Wall Painting & Décor Installation', 'Organizing Room'],
            },
        ],
    },
];
