export const categories = [
    {
        id: 'a',
        name: 'House Chores',
        sub: [
            {
                id: 'a1',
                name: 'Home Cook',
                unit: '/menu set',
                label: 'Type of Service',
                option: ['Delivery', 'Cook at Home', 'Cooking Class', 'Asian', 'Western', 'Vegetarian', 'Pastry', 'Halal'],
            },
            {
                id: 'a2',
                name: 'Dishwashing',
                unit: '/hour',
                label: 'Gender',
                option: ['Male', 'Female'],
            },
            {
                id: 'a3',
                name: 'Trash Pick-Up',
                unit: '/kg',
                label: 'Type of Service',
                option: [
                    'Trash Pick-Up',
                    'Garbage Cleaning',
                    'Trash Collecting',
                    'Sorting Trash',
                    'Organic Waste',
                    'Inorganic Waste',
                    'Recyclable Waste',
                    'Electronic Waste',
                    'Furnitures Waste',
                    'Paper Waste',
                ],
            },
            {
                id: 'a4',
                name: 'Laundry',
                unit: '/kg',
                label: 'Laundry Service',
                option: ['Laundry', 'Ironing', 'Dry Clean', 'Shoe Laundry', 'Bag Laundry', 'Doll Laundry', 'Pillow Laundry'],
            },
            {
                id: 'a5',
                name: 'Delivery',
                unit: '/delivery',
                label: 'Delivery Item',
                option: ['Cooking Gas', 'Drinking Water Gallon'],
            },
        ],
    },
    {
        id: 'b',
        name: 'House Cleaning & Organizing',
        sub: [
            {
                id: 'b1',
                name: 'House Cleaning',
                unit: '/hour',
                label: 'Cleaning Service',
                option: [
                    'Room Cleaning',
                    'Toilet Cleaning',
                    'Window Cleaning',
                    'Ceiling Cleaning',
                    'Attic Cleaning',
                    'Vacuum Cleaning',
                    'Rug Cleaning',
                    'Bed Cleaning',
                    'Leather Furniture Cleaning',
                    'Home Appliances Cleaning',
                    'Sanitizing',
                ],
            },
            {
                id: 'b2',
                name: 'House Handyman',
                unit: '/hour',
                label: 'House Handyman Service',
                option: ['Fixing Broken Furniture', 'Assembling Furniture', 'Wall Painting & Décor Installation', 'Organizing Room'],
            },
            {
                id: 'b3',
                name: 'House Disinfecting',
                unit: '/hour',
                label: 'House Disinfecting Service',
                option: ['Sanitize Surface & Touchpoints', 'Sanitize Floor', 'Sanitize Equipments', 'Sanitize Room'],
            },
        ],
    },
    {
        id: 'c',
        name: 'House Maintenance & Repair',
        sub: [
            {
                id: 'c1',
                name: 'Builder',
                unit: '/day',
                label: 'Builder Service',
                option: [
                    'Soil Excavation',
                    'Landfill',
                    'Concrete Works',
                    'Roof Works',
                    'Flooring Construction',
                    'Wall Painting',
                    'Ceiling Painting',
                    'Wood Painting',
                    'Door Installation & Service',
                    'Window Installation & Service',
                    'Pipe Installation',
                ],
            },
            {
                id: 'c2',
                name: 'Plumber',
                unit: '/day',
                label: 'Plumber Service',
                option: [
                    'Pipes Installation & Service (Pipa)',
                    'Valves Installation & Service (Ledeng)',
                    'Drainage System Service (Drainase)',
                    'Plumbing Fixture Service',
                    'Toilet Installation & Service',
                    'Bathtub Installation & Service',
                    'Water Sink Installation & Service',
                    'Water Heater Installation & Service',
                ],
            },
        ],
    },
];
